/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostIndexRouteImport } from './routes/$host/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as WorkspaceRepoPullPullRequestIdRouteImport } from './routes/$workspace/$repo/pull/$pullRequestId'
import { Route as WorkspaceRepoPullRequestsPullRequestIdRouteImport } from './routes/$workspace/$repo/pull-requests/$pullRequestId'
import { Route as WorkspaceRepoPullPullRequestIdChangesRouteImport } from './routes/$workspace/$repo/pull/$pullRequestId/changes'
import { Route as WorkspaceRepoPullRequestsPullRequestIdDiffRouteImport } from './routes/$workspace/$repo/pull-requests/$pullRequestId/diff'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/$host/',
  path: '/$host/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRepoPullPullRequestIdRoute =
  WorkspaceRepoPullPullRequestIdRouteImport.update({
    id: '/$workspace/$repo/pull/$pullRequestId',
    path: '/$workspace/$repo/pull/$pullRequestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceRepoPullRequestsPullRequestIdRoute =
  WorkspaceRepoPullRequestsPullRequestIdRouteImport.update({
    id: '/$workspace/$repo/pull-requests/$pullRequestId',
    path: '/$workspace/$repo/pull-requests/$pullRequestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceRepoPullPullRequestIdChangesRoute =
  WorkspaceRepoPullPullRequestIdChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => WorkspaceRepoPullPullRequestIdRoute,
  } as any)
const WorkspaceRepoPullRequestsPullRequestIdDiffRoute =
  WorkspaceRepoPullRequestsPullRequestIdDiffRouteImport.update({
    id: '/diff',
    path: '/diff',
    getParentRoute: () => WorkspaceRepoPullRequestsPullRequestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/$host': typeof HostIndexRoute
  '/$workspace/$repo/pull-requests/$pullRequestId': typeof WorkspaceRepoPullRequestsPullRequestIdRouteWithChildren
  '/$workspace/$repo/pull/$pullRequestId': typeof WorkspaceRepoPullPullRequestIdRouteWithChildren
  '/$workspace/$repo/pull-requests/$pullRequestId/diff': typeof WorkspaceRepoPullRequestsPullRequestIdDiffRoute
  '/$workspace/$repo/pull/$pullRequestId/changes': typeof WorkspaceRepoPullPullRequestIdChangesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/$host': typeof HostIndexRoute
  '/$workspace/$repo/pull-requests/$pullRequestId': typeof WorkspaceRepoPullRequestsPullRequestIdRouteWithChildren
  '/$workspace/$repo/pull/$pullRequestId': typeof WorkspaceRepoPullPullRequestIdRouteWithChildren
  '/$workspace/$repo/pull-requests/$pullRequestId/diff': typeof WorkspaceRepoPullRequestsPullRequestIdDiffRoute
  '/$workspace/$repo/pull/$pullRequestId/changes': typeof WorkspaceRepoPullPullRequestIdChangesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/$host/': typeof HostIndexRoute
  '/$workspace/$repo/pull-requests/$pullRequestId': typeof WorkspaceRepoPullRequestsPullRequestIdRouteWithChildren
  '/$workspace/$repo/pull/$pullRequestId': typeof WorkspaceRepoPullPullRequestIdRouteWithChildren
  '/$workspace/$repo/pull-requests/$pullRequestId/diff': typeof WorkspaceRepoPullRequestsPullRequestIdDiffRoute
  '/$workspace/$repo/pull/$pullRequestId/changes': typeof WorkspaceRepoPullPullRequestIdChangesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/oauth/callback'
    | '/$host'
    | '/$workspace/$repo/pull-requests/$pullRequestId'
    | '/$workspace/$repo/pull/$pullRequestId'
    | '/$workspace/$repo/pull-requests/$pullRequestId/diff'
    | '/$workspace/$repo/pull/$pullRequestId/changes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/oauth/callback'
    | '/$host'
    | '/$workspace/$repo/pull-requests/$pullRequestId'
    | '/$workspace/$repo/pull/$pullRequestId'
    | '/$workspace/$repo/pull-requests/$pullRequestId/diff'
    | '/$workspace/$repo/pull/$pullRequestId/changes'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/oauth/callback'
    | '/$host/'
    | '/$workspace/$repo/pull-requests/$pullRequestId'
    | '/$workspace/$repo/pull/$pullRequestId'
    | '/$workspace/$repo/pull-requests/$pullRequestId/diff'
    | '/$workspace/$repo/pull/$pullRequestId/changes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  HostIndexRoute: typeof HostIndexRoute
  WorkspaceRepoPullRequestsPullRequestIdRoute: typeof WorkspaceRepoPullRequestsPullRequestIdRouteWithChildren
  WorkspaceRepoPullPullRequestIdRoute: typeof WorkspaceRepoPullPullRequestIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$host/': {
      id: '/$host/'
      path: '/$host'
      fullPath: '/$host'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/$repo/pull/$pullRequestId': {
      id: '/$workspace/$repo/pull/$pullRequestId'
      path: '/$workspace/$repo/pull/$pullRequestId'
      fullPath: '/$workspace/$repo/pull/$pullRequestId'
      preLoaderRoute: typeof WorkspaceRepoPullPullRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/$repo/pull-requests/$pullRequestId': {
      id: '/$workspace/$repo/pull-requests/$pullRequestId'
      path: '/$workspace/$repo/pull-requests/$pullRequestId'
      fullPath: '/$workspace/$repo/pull-requests/$pullRequestId'
      preLoaderRoute: typeof WorkspaceRepoPullRequestsPullRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/$repo/pull/$pullRequestId/changes': {
      id: '/$workspace/$repo/pull/$pullRequestId/changes'
      path: '/changes'
      fullPath: '/$workspace/$repo/pull/$pullRequestId/changes'
      preLoaderRoute: typeof WorkspaceRepoPullPullRequestIdChangesRouteImport
      parentRoute: typeof WorkspaceRepoPullPullRequestIdRoute
    }
    '/$workspace/$repo/pull-requests/$pullRequestId/diff': {
      id: '/$workspace/$repo/pull-requests/$pullRequestId/diff'
      path: '/diff'
      fullPath: '/$workspace/$repo/pull-requests/$pullRequestId/diff'
      preLoaderRoute: typeof WorkspaceRepoPullRequestsPullRequestIdDiffRouteImport
      parentRoute: typeof WorkspaceRepoPullRequestsPullRequestIdRoute
    }
  }
}

interface WorkspaceRepoPullRequestsPullRequestIdRouteChildren {
  WorkspaceRepoPullRequestsPullRequestIdDiffRoute: typeof WorkspaceRepoPullRequestsPullRequestIdDiffRoute
}

const WorkspaceRepoPullRequestsPullRequestIdRouteChildren: WorkspaceRepoPullRequestsPullRequestIdRouteChildren =
  {
    WorkspaceRepoPullRequestsPullRequestIdDiffRoute:
      WorkspaceRepoPullRequestsPullRequestIdDiffRoute,
  }

const WorkspaceRepoPullRequestsPullRequestIdRouteWithChildren =
  WorkspaceRepoPullRequestsPullRequestIdRoute._addFileChildren(
    WorkspaceRepoPullRequestsPullRequestIdRouteChildren,
  )

interface WorkspaceRepoPullPullRequestIdRouteChildren {
  WorkspaceRepoPullPullRequestIdChangesRoute: typeof WorkspaceRepoPullPullRequestIdChangesRoute
}

const WorkspaceRepoPullPullRequestIdRouteChildren: WorkspaceRepoPullPullRequestIdRouteChildren =
  {
    WorkspaceRepoPullPullRequestIdChangesRoute:
      WorkspaceRepoPullPullRequestIdChangesRoute,
  }

const WorkspaceRepoPullPullRequestIdRouteWithChildren =
  WorkspaceRepoPullPullRequestIdRoute._addFileChildren(
    WorkspaceRepoPullPullRequestIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  HostIndexRoute: HostIndexRoute,
  WorkspaceRepoPullRequestsPullRequestIdRoute:
    WorkspaceRepoPullRequestsPullRequestIdRouteWithChildren,
  WorkspaceRepoPullPullRequestIdRoute:
    WorkspaceRepoPullPullRequestIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
